package util;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
public class GoogleinputTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\kumaro\\Documents\\ChromeDriver\\ChromeDriver.exe");
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
public String waitForWindow(int timeout) {
 try {
   Thread.sleep(timeout);
 } catch (InterruptedException e) {
   e.printStackTrace();
 }
 Set<String> whNow = driver.getWindowHandles();
 Set<String> whThen = (Set<String>) vars.get("window_handles");
 if (whNow.size() > whThen.size()) {
   whNow.removeAll(whThen);
 }
 return whNow.iterator().next();
}
@Test
public void googleinput() {
 driver.get("https://www.google.com/");
 driver.manage().window().setSize(new Dimension(1135, 916));
 driver.findElement(By.name("q")).sendKeys("IDE");
 driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
 driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
 driver.findElement(By.name("btnK")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".g:nth-child(1) > div > .rc .iUh30"));
   Action builder = (Action) new Actions(driver);
   ((Actions) builder).moveToElement(element).perform();
 }
 driver.findElement(By.cssSelector(".bkWMgd:nth-child(1) .LC20lb")).click();
 vars.put("window_handles", driver.getWindowHandles());
 driver.findElement(By.cssSelector(".pluginWrapper:nth-child(3) > .button")).click();
 vars.put("win8338", waitForWindow(2000));
 vars.put("root", driver.getWindowHandle());
 driver.switchTo().window(vars.get("win8338").toString());
 driver.findElement(By.cssSelector(".d-block:nth-child(2) .px-1")).click();
 driver.close();
 driver.switchTo().window(vars.get("root").toString());
 driver.manage().window().
 driver.close();
}
}
